name: Flutter Web Deploy

on:
  push:
    branches:
      - main 

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    # --- මෙන්න මේ කොටස අලුතින් එක් කරන්න ---
    permissions:
      contents: write
    # --------------------------------------

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release --base-href "/Savely-Video-Downloader/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web